using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BareUI.Generators;

/// <summary>
/// Emits a UsePages() builder extension registering every [Page] view with its ViewModel.
/// </summary>
[Generator]
public sealed class PageGenerator : IIncrementalGenerator
{
	sealed record Page(
		string View,
		string ViewModel,
		bool Singleton);


	public void Initialize(
		IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<Page?> pages = context.SyntaxProvider.ForAttributeWithMetadataName(
			"BareUI.PageAttribute",
			static (node, _) => node is ClassDeclarationSyntax,
			static (attribute, _) => Extract(attribute));

		context.RegisterSourceOutput(
			pages.Where(static page => page is not null).Collect(),
			static (production, pages) => production.AddSource("GeneratedPages.g.cs", Emit(pages!)));
	}

	static Page? Extract(
		GeneratorAttributeSyntaxContext context)
	{
		if (context.TargetSymbol is not INamedTypeSymbol view)
			return null;

		// the ViewModel is the type argument of the ContentView<T> base
		for (INamedTypeSymbol? baseType = view.BaseType; baseType is not null; baseType = baseType.BaseType)
			if (baseType is { Name: "ContentView", IsGenericType: true, TypeArguments.Length: 1 }
				&& baseType.ContainingNamespace.ToDisplayString() == "BareUI")
			{
				bool singleton = context.Attributes[0].NamedArguments
					.Any(static argument => argument is { Key: "Singleton", Value.Value: true });

				return new(
					view.ToDisplayString(),
					baseType.TypeArguments[0].ToDisplayString(),
					singleton);
			}

		return null;
	}

	static SourceText Emit(
		ImmutableArray<Page> pages)
	{
		StringBuilder source = new();

		source.AppendLine("// <auto-generated/>");
		source.AppendLine("#nullable enable");
		source.AppendLine("using Microsoft.Extensions.DependencyInjection;");
		source.AppendLine();
		source.AppendLine("namespace BareUI;");
		source.AppendLine();
		source.AppendLine("/// <summary>");
		source.AppendLine("/// Registration for [Page] views, generated at compile time.");
		source.AppendLine("/// </summary>");
		source.AppendLine("public static class GeneratedPages");
		source.AppendLine("{");
		source.AppendLine("\t/// <summary>");
		source.AppendLine("\t/// Registers every [Page] view and its ViewModel.");
		source.AppendLine("\t/// </summary>");
		source.AppendLine("\tpublic static BareApplicationBuilder UsePages(");
		source.AppendLine("\t\tthis BareApplicationBuilder builder) =>");
		source.AppendLine("\t\tbuilder");
		source.AppendLine("\t\t\t.UseServices(services =>");
		source.AppendLine("\t\t\t{");

		foreach (Page page in pages)
			source.AppendLine($"\t\t\t\tservices.AddTransient<global::{page.ViewModel}>();");

		source.AppendLine("\t\t\t})");
		source.AppendLine("\t\t\t.UsePages(pages =>");
		source.AppendLine("\t\t\t{");

		foreach (Page page in pages)
		{
			string lifetime = page.Singleton ? "AddSingleton" : "AddTransient";
			source.AppendLine($"\t\t\t\tpages.{lifetime}((global::{page.ViewModel} vm) => new global::{page.View}(vm));");
		}

		source.AppendLine("\t\t\t});");
		source.AppendLine("}");

		return SourceText.From(source.ToString(), Encoding.UTF8);
	}
}
