<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>

		<SkeleKitPackageVersion>0.1.1</SkeleKitPackageVersion>
		<SkeleKitUseProjectReferences Condition="'$(MSBuildProjectName)' == 'SkeleKit.Template'">true</SkeleKitUseProjectReferences>

		<ValidateXcodeVersion>false</ValidateXcodeVersion>
	</PropertyGroup>
</Project>
